name: testapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.0
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  mobx: ^2.5.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  image: ^4.3.0
  toastification: ^3.0.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
#    - assets/lottiefile/
